### ISSUE TITLE
请问怎样在代码中动态设置颜色

### ISSUE THREAD

**Issue by woxingxiao** [H07000223/FlycoRoundView#2]
我试过调用 .getDelegate().setBackgroundColor()和.getDelegate().setBackgroundPressColor()都没效果诶

**Comment by H07000223** [comment]
用的是哪个控件~Android什么版本~我去试试

**Comment by woxingxiao** [comment]
RoundTextView, RoundxxLayout都不行，5.1.1

**Comment by H07000223** [comment]
我用了genymotion 5.1.0虚拟机和三星5.0.1都是可以~我这没你这5.1.1~😂😂😂

**Comment by woxingxiao** [comment]
解决了：.getDelegate().setBackgroundColor(context.getResources().getColor(R.color.red))才有效果，
.getDelegate().setBackgroundColor(R.color.red);则没有效果

**Comment by H07000223** [comment]
嗯,解决就好~R.color.red资源索引值~方法需要的是Color int值~😂

**Comment by woxingxiao** [comment]
建议两种方式都支持啊，免得别人再踩坑😂

**Comment by H07000223** [comment]
额~没这个打算,你可以试试View自带的setBackgroundColor也是不支持的R.color.red~

**Comment by woxingxiao** [comment]
怪我没说清楚，setBackgroundResource和setBackgroundColor。Thanks, anyway.
