### ISSUE TITLE
Ripple effect support

### ISSUE THREAD

**Issue by rafakob** [H07000223/FlycoRoundView#3]
Hello,
I've just tested your library, so far it looks promising. Have you thought about supporting ripple effect background? It's kind of a must-have feature these days.

**Comment by H07000223** [comment]
Thanks for your advice, I will consider about it. Since I am poor at this feature,  I need time to do some research. If all goes well, maybe next version will support ripple effect .

**Comment by H07000223** [comment]
I find a ripple effect lib that can work with RoundView. It may help you at present. [RippleEffect](https://github.com/traex/RippleEffect)

**Comment by rafakob** [comment]
Thanks for a reply. I've heard about that lib, though I prefer "more native" solution. What I mean by that is on API >= 21 use RippleDrawable, and on pre-lollipop just highlight background (without any additional animations). You may find it useful -> http://stackoverflow.com/a/28353890/1885562

I've looked at your code and it should be easy to implement it. From the user perspective it should IMO looks like this:

```
rv_backgroundColor = red
isRippleEnabled = true

API21: bg red, default ripple color
PRE: bg red, ripple no effect
```

```
rv_backgroundColor = red
rv_backgroundRippleColor = blue
isRippleEnabled = true

API21: bg red, ripple blue
PRE: bg red, highlight blue
```

**Comment by H07000223** [comment]
Already done in 1.1.4 ~ use pressColor as rippleColor
